apiVersion: v1
kind: List
items:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      template: gogs-template
      app: gogs
{% if ocp_project_label is defined %}
      project: {{ ocp_project_label }}
{% endif %}
    name: gogs-data
    namespace: {{ ocp_project_name }}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: build-pipeline-gogs-data
    selector:
      matchLabels:
        pv: build-pipeline-gogs-data
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      template: gogs-template
      app: gogs
{% if ocp_project_label is defined %}
      project: {{ ocp_project_label }}
{% endif %}
    name: gogs-mysql
    namespace: {{ ocp_project_name }}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: build-pipeline-gogs-mysql
    selector:
      matchLabels:
        pv: build-pipeline-gogs-mysql