apiVersion: v1
kind: Template
metadata:
  name: mysql-template
  annotations:
    description: "A default MySQL server"
    tags: quickstart,instant-app,git,gogs,database
  labels:
    template: mysql-template
    app: mysql
{% if ocp_project_label is defined %}
    project: {{ ocp_project_label }}
{% endif %}
objects:
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      template: mysql-template
      app: mysql
{% if ocp_project_label is defined %}
      project: {{ ocp_project_label }}
{% endif %}
    name: mysql
    namespace: {{ ocp_project_name }}
  spec:
    ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentconfig: mysql
    sessionAffinity: None
    type: ClusterIP
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: "a database service for the builder"
    labels:
      app: {{ ocp_application }}
      template: mysql-template
{% if ocp_project_label is defined %}
      project: {{ ocp_project_label }}
{% endif %}
  spec:
    strategy:
      type: "Recreate"
    triggers:
    - type: "ConfigChange"
    replicas: 1
    selector:
      name: "${DATABASE_SERVICE_NAME}"
    template:
      metadata:
        name: "${DATABASE_SERVICE_NAME}"
        labels:
          template: mysql-template
          app: mysql
          name: "${DATABASE_SERVICE_NAME}"
{% if ocp_project_label is defined %}
          project: {{ ocp_project_label }}
{% endif %}
      spec:
        volumes:
        - name: "mysql-data"
          persistentVolumeClaim:
            claimName: mysql-mysql
        containers:
        - name: mysql
          image: mysql:5.6
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: "mysql-data"
            mountPath: "/var/lib/mysql"
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD='${DATABASE_PASSWORD}' mysql -h 127.0.0.1 -u gogs -D default -e 'SELECT 1'
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
          env:
          - name: "MYSQL_USER"
            value: "${DATABASE_USER}"
          - name: "MYSQL_PASSWORD"
            value: "${DATABASE_PASSWORD}"
          - name: "MYSQL_DATABASE"
            value: "${DATABASE_NAME}"
          - name: "MYSQL_ROOT_PASSWORD"
            value: "${DATABASE_PASSWORD}"
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
        serviceAccount: mysql
        serviceAccountName: mysql
        securityContext:
          supplementalGroups: [${DATABASE_NFS_GID}]
parameters:
- name: "DATABASE_SERVICE_NAME"
  displayName: "Database Service Name"
  required: true
  value: "mysql"- name: "DATABASE_NAME"
  displayName: "Database Name"
  required: true
  value: "default"
- name: "DATABASE_USER"
  displayName: "Database User"
  required: true
  value: "user"
- name: "DATABASE_PASSWORD"
  displayName: "Database Password"
  generate: "expression"
  from: "[a-zA-Z0-9]{16}"
- name: "DATABASE_NFS_GID"
  displayName: "Database NFS Mount GID"
  required: true
  value: "{{ mysql_nfs_gid }}"
- name: "MEMORY_LIMIT"
  displayName: "Memory Limit"
  description: "Maximum amount of memory the MySQL container can use."
  required: true
  value: "512Mi"
- name: "CPU_LIMIT"
  displayName: "CPU Limit"
  description: "Maximum amount of CPU the MySQL container can use."
  required: true
  value: "1000m"
- name: "MEMORY_REQUEST"
  displayName: "Memory Request"
  description: "Default amount of memory the MySQL container wants to use."
  required: true
  value: "256Mi"
- name: "CPU_REQUEST"
  displayName: "CPU Request"
  description: "Default amount of CPU the MySQL container wants to use."
  required: true
  value: "200m"
