apiVersion: v1
kind: Template
items:
- apiVersion: v1
  kind: Project
  metadata:
    name: {{ ocp_project_name }}
    label: project={{ ocp_project_label }}
    annotations:
      openshift.io/requester: {{ ocp_project_requester }}
      openshift.io/description: {{ ocp_project_description }}
      openshift.io/display-name: {{ ocp_project_display_name }}
  spec:
    finalizers:
    - kubernetes
    - openshift.io/origin
- apiVersion: v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: {{ ocp_project_name }}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:{{ ocp_project_name }}
  groupNames:
  - system:serviceaccounts:{{ ocp_project_name }}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: {{ ocp_project_name }}
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:{{ ocp_project_name }}:builder
  groupNames: null
- apiVersion: v1
  kind: RoleBinding
  groupNames:
  - {{ ocp_project_admin_group }}
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: {{ ocp_project_name }}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:{{ ocp_project_name }}:deployer
- apiVersion: v1
  kind: RoleBinding
  groupNames:
  - {{ ocp_project_admin_group }}
  metadata:
    creationTimestamp: null
    name: admin
    namespace: {{ ocp_project_name }}
  roleRef:
    name: admin
  subjects:
  - kind: Group
    name: {{ ocp_project_admin_group }}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: edit
    namespace: {{ ocp_project_name }}
  roleRef:
    name: edit
  subjects:
  - kind: Group
    name: {{ ocp_project_user_group }}
  groupNames:
  - {{ ocp_project_user_group }}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: basic-user
    namespace: {{ ocp_project_name }}
  roleRef:
    name: basic-user
  subjects:
  - kind: Group
    name: {{ ocp_project_ro_group }}
  groupNames:
  - {{ ocp_project_ro_group }}